In [5]:
from numpy import *
filename='/home/dandelion/文档/python/machinelearninginaction/Ch02/datingTestSet.txt'
fr = open(filename)
numberOfLines = len(fr.readlines())         #get the number of lines in the file
returnMat = zeros((numberOfLines,3))        #prepare matrix to return


In [9]:
fr = open(filename)
fr.readline()


'40920\t8.326976\t0.953952\tlargeDoses\n'

In [12]:
line=fr.readline()

In [15]:
line

'75136\t13.147394\t0.428964\tdidntLike\n'

In [16]:
line.strip()

'75136\t13.147394\t0.428964\tdidntLike'

In [17]:
line.split('\t')

['75136', '13.147394', '0.428964', 'didntLike\n']

In [18]:
line.strip().split('\t')[0:3]

['75136', '13.147394', '0.428964']

In [19]:
line.strip().split('\t')[-1]

'didntLike'

In [20]:
classLabelVector = []

In [21]:
int(line.strip().split('\t')[-1])

ValueError: invalid literal for int() with base 10: 'didntLike'

In [24]:
def file2matrix(filename):
    fr = open(filename)
    numberOfLines = len(fr.readlines())         #get the number of lines in the file
    returnMat = zeros((numberOfLines,3))        #prepare matrix to return
    classLabelVector = []                       #prepare labels return   
    fr = open(filename)
    index = 0
    for line in fr.readlines():
        line = line.strip()
        listFromLine = line.split('\t')
        returnMat[index,:] = listFromLine[0:3]
        classLabelVector.append(listFromLine[-1])
        index += 1
    return returnMat,classLabelVector

In [25]:
from numpy import *
filename='/home/dandelion/文档/python/machinelearninginaction/Ch02/datingTestSet.txt'
datingDataMat,datingLabels =file2matrix(filename)
datingDataMat,datingLabels

(array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
        [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
        [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
        ...,
        [2.6575000e+04, 1.0650102e+01, 8.6662700e-01],
        [4.8111000e+04, 9.1345280e+00, 7.2804500e-01],
        [4.3757000e+04, 7.8826010e+00, 1.3324460e+00]]),
 ['largeDoses',
  'smallDoses',
  'didntLike',
  'didntLike',
  'didntLike',
  'didntLike',
  'largeDoses',
  'largeDoses',
  'didntLike',
  'largeDoses',
  'didntLike',
  'didntLike',
  'smallDoses',
  'didntLike',
  'didntLike',
  'didntLike',
  'didntLike',
  'didntLike',
  'smallDoses',
  'largeDoses',
  'smallDoses',
  'didntLike',
  'smallDoses',
  'largeDoses',
  'smallDoses',
  'largeDoses',
  'smallDoses',
  'largeDoses',
  'smallDoses',
  'didntLike',
  'largeDoses',
  'didntLike',
  'largeDoses',
  'didntLike',
  'smallDoses',
  'didntLike',
  'didntLike',
  'smallDoses',
  'largeDoses',
  'largeDoses',
  'didntLike',
  'smallDoses',
  

In [26]:
datingDataMat[:,1]

array([8.3269760e+00, 7.1534690e+00, 1.4418710e+00, 1.3147394e+01,
       1.6697880e+00, 1.0141740e+01, 6.8307920e+00, 1.3276369e+01,
       8.6315770e+00, 1.2273169e+01, 3.7234980e+00, 8.3858790e+00,
       4.8754350e+00, 4.6800980e+00, 1.5299570e+01, 1.8894610e+00,
       7.5167540e+00, 1.4239195e+01, 0.0000000e+00, 1.0528555e+01,
       3.5402650e+00, 2.9915510e+00, 5.2978650e+00, 6.5938030e+00,
       2.8167600e+00, 1.2458258e+01, 0.0000000e+00, 9.9686480e+00,
       1.3648380e+00, 2.3045300e-01, 1.1865402e+01, 1.2046000e-01,
       8.5452040e+00, 5.8566490e+00, 9.6656180e+00, 9.7787630e+00,
       4.9329760e+00, 2.2162460e+00, 1.4305636e+01, 1.2591889e+01,
       3.4246490e+00, 0.0000000e+00, 8.5338230e+00, 9.8295280e+00,
       1.1492186e+01, 3.5709680e+00, 1.7712280e+00, 3.5139210e+00,
       4.3981720e+00, 4.2768230e+00, 5.9460140e+00, 1.3798970e+01,
       1.0393591e+01, 3.0075770e+00, 1.0319380e+00, 4.7512120e+00,
       3.6922690e+00, 1.0448091e+01, 1.0585786e+01, 1.6045010e

In [27]:
datingDataMat[1,:]

array([1.448800e+04, 7.153469e+00, 1.673904e+00])

In [28]:
import matplotlib
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)

In [30]:
ax.scatter(datingDataMat[:,1], datingDataMat[:,2])

In [31]:
plt.show()

In [32]:
ax.scatter() --help


/home/dandelion/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Tried to set a label via parameter 'y' in func 'scatter' but couldn't find such an argument.
(This is a programming error, please report to the Matplotlib list!)
  """Entry point for launching an IPython kernel.


TypeError: scatter() missing 2 required positional arguments: 'x' and 'y'

In [33]:
help(ax.scatter())

/home/dandelion/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Tried to set a label via parameter 'y' in func 'scatter' but couldn't find such an argument.
(This is a programming error, please report to the Matplotlib list!)
  """Entry point for launching an IPython kernel.


TypeError: scatter() missing 2 required positional arguments: 'x' and 'y'